protected/controllers/SiteController.php
<?php

class SiteController extends Controller {
    
    public $layout = '//layouts/company';
    
    /**
 	 * Declares class-based actions.
	 */
	public function actions() {
		return array(
			# captcha action renders the CAPTCHA image displayed on the contact page
			#'captcha'=>array(
			#	'class'=>'CCaptchaAction',
			#	'backColor'=>0xFFFFFF,
			#),
			// page action renders "static" pages stored under 'protected/views/site/pages'
			// They can be accessed via: index.php?r=site/page&view=FileName
			'page'=>array(
				'class'=>'CViewAction',
			),
		);
	}
    public function filters() {
        return array(
            'accessControl', // perform access control for CRUD operations
        );
    }

    public function accessRules() {
        return array(
            array('allow',  // all users
                  'actions'=>array(
                      'index', 'error', 
                      'changeLanguage',
                      'signup', 'signupdoctor', 
                      'login', 'logout', 
                      'about', 'pricing', 
                      'terms', 'recruitment',
                      'forgotpassword',
                      'checkout', 'finish', 
                      'review',
                      'doctor',
                      'article', 'articleDetails'
                  ),
                  'users'=>array('*'),
            ),
            array('deny',  // deny all users
                'users'=>array('*'),
            ),
        );
    }
    
    public function actionForgotPassword() {
        $this->layout = '//layouts/system';
        $this->render('forgotpassword');
    }
    
    public function actionSignupDoctor() {
        $this->layout = '//layouts/system';
        $this->render('signupdoctor');
    }
    
    public function actionSignup() {
        $this->layout = '//layouts/system';
        $this->render('signup');
    }
    
    public function actionLogin() {
        $this->layout = '//layouts/system';
        $this->render('login');
    }
    
    public function actionArticle() {
        $this->render('article');
    }
    
    public function actionArticleDetails() {
        $this->render('article-details');
    }
    
    public function actionDoctor() {
        $this->render('doctor');
    }
    
    public function actionReview() {
        $this->render('review');
    }
    
    public function actionCheckout() {
        //$this->layout = '//layouts/company2';
        $this->render('checkout');
    }
    
    public function actionFinish() {
        //$this->layout = '//layouts/company2';
        $this->render('finish');
    }
    
    public function actionAbout() {
        //$this->layout = '//layouts/company2';
        $this->render('about');
    }
    
    public function actionPricing() {
        $this->render('pricing');
    }
    
    public function actionTerms() {
        $this->render('terms');
    }
    
    public function actionRecruitment() {
        $this->render('recruitment');
    }
    
    /**
     * This is the default 'index' action that is invoked
     * when an action is not explicitly requested by users.
     */
    public function actionIndex() {        
        #if (Yii::app()->user->isGuest) {
    #    $this->render('index');
    #} else {
    #    if (Yii::app()->user->checkAccess('admin')) {
    #        $this->redirect(array('admin/index'));
    #    } else {
    #        $this->redirect(array('user/accountBalance', 'id'=>Yii::app()->user->_id));
    #    }
        #}
        $this->layout = '//layouts/homepage';
    $this->render('index');
//        $this->redirect('patient/index');
    }
    
    public function actionChangeLanguage() {
        /* Change the session's language if the requested language is
         * supported */
//        Util::changeLanguage(Util::get($_GET, 'lang'));
//        /* Return to the previous page */
//        $returnUrl = Yii::app()->request->urlReferrer;
//        if (!$returnUrl)
//            $returnUrl = '/';
//        $this->redirect($returnUrl);
        
        if (isset($_POST['lang']))
        {
            $language = $_POST['lang'];
            if (Util::isLanguageSupported($language)) {
                Yii::app()->session['language'] = $language;
                Yii::app()->language = $language;

                Util::returnJSON(array('success' => true));
            }
            Util::returnJSON(array('success' => false));
        }
        Util::returnJSON(array('success' => false));
    }


    private function loadUser() {
      return User::model()->findbyPk(Yii::app()->user->_id);
    }

    /**
     * This is the action to handle external exceptions.
     */
    public function actionError() {
        if ($error = Yii::app()->errorHandler->error) {
        if (Yii::app()->request->isAjaxRequest) {
                    echo $error['message'];
        }
            else {
                    $this->render('error', $error);
        }
        }
    }

    /**
     * Displays the contact page
     */
//	public function actionContact() {
//		$model = new ContactForm;
//		if (isset($_POST['ContactForm'])) {
//			$model->attributes=$_POST['ContactForm'];
//			if ($model->validate()) {
//				$headers = "From: {$model->email}\r\nReply-To: {$model->email}";
//				mail(Yii::app()->params['adminEmail'],$model->subject,$model->body,$headers);
//                Yii::app()->user->setFlash('contact',
//                    'Thank you for contacting us. We will respond to you as soon as possible.');
//				$this->refresh();
//			}
//		}
//		$this->render('contact',array('model'=>$model));
//        $this->render('contact');
//	}


    /**
     * Displays the login page
     */
//	public function actionLogin() {
//		$model = new LoginForm;
//		// collect user input data
//		if (isset($_POST['LoginForm'])) {
//			$model->attributes=$_POST['LoginForm'];
//			// validate user input and redirect to the previous page if valid
//			if($model->validate())
//				$this->redirect(Yii::app()->user->returnUrl);
//		}
//		// display the login form
//		$this->render('login',array('model'=>$model));
//	}

    /**
     * Logs out the current user and redirect to homepage.
     */
    public function actionLogout() {
        Yii::app()->user->logout();
        $this->redirect(Yii::app()->homeUrl);
    }
}

protected/controllers/Z_UserController.php
<?php

class UserController extends Controller {
    const PAGE_SIZE = 10;

    /**
     * @var string specifies the default action
     */
    public $defaultAction='admin';

    /**
     * @var CActiveRecord the currently loaded data model instance.
     */
    private $_user;

    /**
     * @return array action filters
     */
    public function filters() {
        return array(
            'accessControl', // perform access control for CRUD operations
        );
    }

    /**
     * Specifies the access control rules.
     * This method is used by the 'accessControl' filter.
     * @return array access control rules
     */
    public function accessRules() {
        return array(
            /*array('allow',  // all users
                'actions'=>array('create', 'confirm', 'welcome',
                				'reset', 'resetThanks',
                                'sendActivationEmail'),
                'users'=>array('*'),
            ),
            array('allow', # logged in users
                    'actions'=>array('update', 'welcome', 'activationNeeded', 'changePassword'),
                    'users'=>array('@'),
                ),*/
            array('allow', # admins
                'actions'=>array('admin'),
                'roles'=>array('admin'),
                'users'=>array('@'),
            ),
            array('deny',  // deny all users
                'users'=>array('*'),
            ),
        );
    }

    /**
     * Shows a particular user.
     */
    public function actionShow() {
        #if (Yii::app()->user->checkAccess('showUser')) {
        #}
        $this->render('show',array('user'=>$this->loadUser()));
    }

    /**
     * Creates a new user.
     * If creation is successful, the browser will be redirected to the 'show' page.
     */

    # Create new account
    public function actionCreate() {
        $user = new User;
        $this->performAjaxValidation($user);
        if (isset($_POST['User'])) {
            $user->attributes = $_POST['User'];

            $attrs = $_POST['User'];
            $user->username = trim($attrs['username']);
            $user->email = trim($attrs['email']);
            $user->password = $attrs['password'];
            $user->password_repeat = $attrs['password_repeat'];
            $user->unique_id  = $user->generatePassword(20);

            $user->is_approved = 1;

            if ($user->validate('insert')) {
                $user->encryptPassword();

                if ($user->save(false)) {
                    # Create default objects for user here

                    $this->sendActivationEmail($user);

                    $this->redirect(array('welcome', 'id'=>$user->id));
                }
                else {
                    Yii::log(__FUNCTION__."> create failed", 'warning');
                }
            }
            else {
                Yii::log(__FUNCTION__."> validation failed", 'warning');
            }
        }
        $this->render('create', array('model'=>$user)) ;
    }

    protected function performAjaxValidation($model) {
        if (isset($_POST['ajax']) && $_POST['ajax']==='user-form') {
            echo CActiveForm::validate($model);
            Yii::app()->end();
        }
    }

    /**
     * Updates a particular user.
     * If update is successful, the browser will be redirected to the 'show' page.
     */
    public function actionUpdate() {
        $user = $this->loadUser();
        $this->performAjaxValidation($user);
        #if (!Yii::app()->user->checkAccess('updateOwnUser', array('user'=>$user))) {
        #    Yii::log(__FUNCTION__."> Unauthorized", 'debug');
        #    throw new CHttpException(403, 'You are not authorized to perform this action.');
        #}

        if (isset($_POST['User'])) {
            $user->attributes = $_POST['User'] ;
            $attrs = $_POST['User'];

            $password = $user->password_new = $attrs['password'];
            $user->password_repeat = $attrs['password_repeat'];

            if ($user->validate('update')) {
                if ($password != '') {
                    $user->encryptPassword();
                }

                if ($user->save(false)) {
                    Yii::app()->user->setFlash('notice', 'Updated');
                    $this->redirect(array('site/index'));
                }
                else {
                    Yii::log(__FUNCTION__."> Update failed", 'warning');
                }

            }
            else {
                Yii::log(__FUNCTION__."> validation failed", 'warning');
            }
        }
        $user->password = $user->password_repeat = '';
        $this->render('update', array('model'=>$user)) ;
    }

    /**
     * Deletes a particular user.
     * If deletion is successful, the browser will be redirected to the 'list' page.
     */
    public function actionDelete() {
        if (Yii::app()->request->isPostRequest) {
            # we only allow deletion via POST request
            $user = $this->loadUser();
            $auth = Yii::app()->authManager;
            $auth->revoke($user->getRoleName(), $user->username);
            $user->delete();
            $this->redirect(array('list'));
        }
        else {
            throw new CHttpException(500,'Invalid request. Please do not repeat this request again.');
        }
    }

    # Confirm email works
	public function actionConfirm() {
		$key = $_GET['key'] ;
		User::model()->updateAll(array('is_activated'=>1),'unique_id=:unique_id', array(':unique_id'=>$key));

        $user = User::model()->findByAttributes(array('unique_id' => $key));
        if (!$user->is_approved) {
            $this->sendNotificationEmail($user);
        }

		$this->render('confirm', array('user'=>$user));
	}

    public function actionWelcome() {
        $this->render('welcome', array('user'=>$this->loadUser())) ;
    }

    public function actionActivationNeeded() {
        $this->render('activationNeeded', array('user'=>$this->loadUser())) ;
    }

    # Look up user and reset password
    public function actionReset() {
    	$email='';
        //$this->render('reset',array('user'=>$this->loadUser())) ;
        if (isset($_REQUEST["reset_user"])) {
            $reset_user = $_REQUEST["reset_user"];
            Yii::log("reset $reset_user", 'debug');
            $user = User::model()->findByAttributes(array('username' => $reset_user));
            if ($user !== null) {
                Yii::log(__FUNCTION__."> reset found user $reset_user", 'debug');
                $user->password = $user->generatePassword(8);
                $user->encryptPassword();

                if ($user->save()) {
                    $this->sendPasswordEmail($user);
                }
                else {
                    Yii::log(__FUNCTION__."> Error: could not save new user password", 'error');
                }
            }
            else {
                Yii::log(__FUNCTION__."> User account not found for user $reset_user", 'error');
            }
            $this->redirect(array('user/resetThanks'));
        }
        $this->render('reset', array('email'=>$email));
    }

    public function actionResetThanks() {
        $this->render('resetThanks');
    }

    # Reset password and send it to user in email
    public function actionLostPass() {
        $user = $this->loadUser();
        if (isset($_POST['User'])) {
            $user->attributes = $_POST['User'];
            $user->password = $user->generatePassword(8);
            $user->encryptPassword();

            if ($user->save()) {
                $this->sendPasswordEmail($user);
            }
            else {
                Yii::log("Error saving new user password", 'error');
            }
        }
        $this->render('lostpass', array('user'=>$user)) ;
    }

    # Change user password
    public function actionChangePassword() {
        $user = $this->loadUser(Yii::app()->user->db_id); // only allows the current user
        if (isset($_POST['User'])) {
            $user->attributes=$_POST['User'];
            $user->encryptPassword();

            if ($user->save()) {
                $this->redirect(array('passwordChanged'));
            }
            else {
                Yii::log("password update failed", 'warning');
                #Yii::app()->user->setFlash('contact','Password update failed');
            }
        }
        $this->render('changePassword',array('user'=>$user));
    }

    public function actionPasswordChanged() {
        $this->render('passwordChanged') ;
    }

    # Send account activation email
    private function sendActivationEmail($user) {
        $app_email_name = Yii::app()->params['app_email_name'];
        $app_email = Yii::app()->params['app_email'];
        $email_prefix = Yii::app()->params['email_prefix'];
        $headers = "From: $app_email_name <$app_email>\r\n"; //optional header fields
        ini_set('sendmail_from', $app_email);

        $recipient = $user->email;
        $subject = $email_prefix . "Welcome to " . Yii::app()->name;
        $url = $this->createAbsoluteUrl('user/confirm', array('key' => $user->unique_id));
        $body = <<<EO_MAIL
Thanks for joining!

To confirm that your email works, please click on this link:
$url

EO_MAIL;
        mail($recipient, $subject, $body, $headers);
        Yii::log("Sent email to $recipient, $subject");
    }

    // Send password email
    private function sendPasswordEmail($user) {
        $app_email_name = Yii::app()->params['app_email_name'];
        $app_email = Yii::app()->params['app_email'];
        $email_prefix = Yii::app()->params['email_prefix'];
        $headers = "From: $app_email_name <$app_email>\r\n"; //optional header fields
        ini_set('sendmail_from', $app_email);

        $recipient = $user->email;
        $subject = $email_prefix . "Password reset";
        $password_unhashed = $user->passwordUnHashed;
        $url = $this->createAbsoluteUrl('site/login');
        $body = <<<EO_MAIL

protected/views/site/about.php
<div class="container">
    <div class="col-sm-8">
        
    </div>
    <div class="col-sm-4">
        
    </div>
</div>

protected/views/site/article-details.php
<div class="container">
    <div class="col-sm-12 text-center">
        <h3>Blood Pressure</h3>
    </div>
    <div class="col-sm-8 margin-t article-list">
        <h4 class="red">Huyết áp - Tim mạch</h4>
        <div class="article-content">
            Có 2 vấn đề sức khỏe đang gây nhức nhối với cộng đồng đó là huyết áp cao và huyết áp thấp. Người ta nhắc nhiều đến các chỉ số “huyết áp” kèm theo thông điệp theo dõi chỉ số huyết áp như theo dõi chính chỉ số sức khỏe của bạn và gia đình. Vậy huyết áp là gì? Thế nào được coi là huyết áp cao và huyết áp thấp? Mời bạn đọc cùng tham khảo một số thông tin bổ ích về huyết áp qua bài viết dưới đây.<br>
            <br>
            <p class="text-center"><img src="/img/article/1HuyetAp.jpg"></p>
                Huyết áp là gì ?<br>
<br>
                Huyết áp là áp lực máu cần thiết tác động lên thành động mạch nhằm đưa máu đến nuôi dưỡng các mô trong cơ thể. Huyết áp được tạo ra do lực co bóp của tim và sức cản của động mạch.<br>
<br>
                Ở người bình thường, huyết áp ban ngày cao hơn ban đêm, huyết áp hạ xuống thấp nhất vào khoảng 1-3 giờ sáng khi ngủ say và huyết áp cao nhất từ 8 – 10 giờ sáng. Khi vận động, gắng sức thể lực, căng thẳng thần kinh hoặc khi xúc động mạnh đều có thể làm huyết áp tăng lên. Và ngược lại, khi cơ thể được nghỉ ngơi, thư giãn, huyết áp có thể hạ xuống.<br>
<br>
                Khi bị lạnh gây co mạch, hoặc dùng một số thuốc co mạch hoặc thuốc co bóp cơ tim, ăn mặn có thể làm huyết áp tăng lên. Ở môi trường nóng, ra nhiều mồ hôi, bị tiêu chảy … hoặc dùng thuốc giãn mạch có thể gây hạ huyết áp.<br>
<br>
                Huyết áp được thể hiện bằng 2 chỉ số:<br>
<br>
                Huyết áp tối đa (còn gọi là huyết áp tâm thu hoặc ngắn gọn là số trên), bình thường từ 90 đến 139 mm Hg (đọc là milimét thuỷ ngân).<br>
                Huyết áp tối thiểu (còn gọi là huyết áp tâm trương hoặc ngắn gọn là số dưới), bình thường từ 60 đến 89 mm Hg.<br>
                Mỗi người phải luôn biết và nhớ hai chỉ số huyết áp của mình.<br>
<br>
                Thế nào là huyết áp cao và huyết áp thấp?<br>
<br>
                Trên thực tế, cả 2 tình trạng huyết áp cao và huyết áp thấp đều gây nguy hiểm tới sức khỏe của người bệnh. Bất cứ ai trong số chúng ta cũng đều nên nắm rõ các chỉ số huyết áp để theo dõi huyết áp của mình nằm trong vùng nào để điều chỉnh chế độ ăn uống và lối sống cho phù hợp.<br>
<br>
<ul>
    <li>Huyết áp bình thường: Đối với người trưởng thành, khi các chỉ số huyết áp tâm thu dưới 120mmHg và huyết áp tâm trương dưới 80mmHg thì được gọi là huyết áp bình thường.</li>
    <li>Huyết áp cao : Khi chỉ số huyết áp tâm thu lơn hơn 140 mmHG và huyết áp tâm trương lớn hơn 90 mmHg thì được chẩn đoán là huyết áp cao.</li>
    <li>Tiền cao huyết áp là mức giá trị của các chỉ số huyết áp nằm giữa huyết áp bình thường và cao huyết áp (Huyết áp tâm thu từ 120-139 mmHg hoặc huyết áp tâm trương từ 80-89 mmHg)</li>
    <li>Huyết áp thấp: Hạ huyết áp (huyết áp thấp) được chẩn đoán khi huyết áp tâm thu dưới 90 mmHg hoặc giảm 25 mmHg so với bình thường.</li>
    <li>Để kết luận một người bị tăng huyết áp hay không người ta cần căn cứ vào trị số huyết áp của nhiều ngày. Đo đó phải đo huyết áp thường xuyên, nhiều lần trong ngày, theo dõi trong nhiều ngày. Phải đo huyết áp cả hai tay sau 5 phút nằm nghỉ và sau tối thiểu 1 phút ở tư thế đứng. Ở một số người huyết áp có thể tăng nhất thời khi quá xúc cảm, stress, hoặc sau khi uống rượu, bia, sau tập luyện, lao động nặng… chẳng hạn.</li>
</ul>
<br>
                Huyết áp cao và huyết áp thấp có nguy hiểm không?<br>
<br>
                Không ai phủ nhận mức độ nguy hiểm của huyết áp cao và huyết áp thấp. Người ta coi đây là các sát thủ thầm lặng với sức khỏe con người bởi diễn biến âm thầm, các triệu chứng không rõ ràng và các biến chứng nguy hiểm mà nó để lại.<br>
                do huyet ap Huyết áp là gì ?<br>
<br>
<p class="text-center"><img src="/img/article/1do-huyet-ap.jpg"></p>
                <p class="text-center">Đo huyết áp thường xuyên là biện pháp tối ưu kiểm soát huyết áp của bạn và gia đình<br></p>
<br>
                Huyết áp cao nguy hiểm như thế nào?<br>
<br>
                Nếu như huyết áp cao là bệnh thuờng gặp và gia tăng theo tuổi, là nguyên nhân gây tử vong và di chứng thần kinh nặng nề như liệt nửa người, hôn mê với đời sống thực vật, đồng thời có thể thúc đẩy suy tim, thiếu máu cơ tim làm ảnh hưởng nhiều đến chất lượng sống (không cảm thấy khoẻ khoắn, mất khả năng lao động) và gia tăng khả năng tử vong. Huyết áp cao còn là một trong những yếu tố nguy cơ của đột quỵ, nhồi máu cơ tim, suy tim và phình động mạch, ngoài ra nó còn là nguyên nhân gây ra suy thận mãn và biến chứng ở mắt. Tăng áp lực máu động mạch sẽ dẫn tới giảm tuổi thọ trung bình.<br>
<br>
                Nếu không được điều trị kịp thời, huyết áp cao có thể gây nhiều biến chứng nguy hiểm cho sức khỏe:<br>
<br>
<ul>
    <li>Biến chứng tức thời: Có thể nguy hiểm đến tính mạng, gồm tai biến mạch máu não, nhồi máu cơ tim cấp, bóc tách động mạch chủ, phù phổi cấp, suy thận cấp.</li>
    <li>Biến chứng lâu dài: Xảy ra nếu bệnh nhân sau một thời gian dài tăng huyết áp mà không được chẩn đoán và điều trị đúng. Biến chứng gồm: Rối loạn tiền đình, bệnh lý mắt, tim to, suy tim, đau thắt ngực do thiếu máu cục bộ cơ tim, suy thận mạn, đau cách hồi.</li>
</ul>
                <br>
                Huyết áp thấp nguy hiểm như thế nào?<br>
<br>
                Nếu so sánh với huyết áp cao, huyết ấp thấp trước mắt không dẫn đến biến chứng như tai biến mạch máu não, nghẽn tắc cơ tim nên nhiều người chủ quan với căn bệnh này. Tuy nhiên, ít người biết được rằng huyết áp thấp cũng có thể gây ra các biến chứng nguy hiểm không kém.<br>
<br>
                Khi người bệnh bị tụt huyết áp nhiều lần, hệ thống thần kinh bị suy giảm chức năng, cơ thể không tự kịp điều chỉnh để cung cấp đủ dinh dưỡng và oxy cho các cơ quan có chức năng sống còn như não, tim, thận gây ra các tổn thương cho các cơ quan này.<br>
<br>
                Nếu không được điều trị kịp thời, bệnh huyết áp thấp có thể dẫn đến tình trạng đau thắt ngực, nhồi máu cơ tim, suy thận… thậm chí nguy hiểm đến tính mạng. Nhiều trường hợp huyết áp thấp có thể dẫn tới tai biến mạch máu não, trong đó phần lớn là nhồi máu não, tỷ lệ này chiếm khoảng 30%. Ngoài ra, người bị tụt huyết áp cấp có thể gây sốc, đặc biệt nguy hiểm đến tính mạng trong những trường hợp như đang lái xe, làm việc trên tầng cao… Nếu huyết áp thấp kéo dài, còn làm cho các cơ quan thận, gan, tim, phổi suy yếu nhanh chóng.<br>
            <br>
        </div>
    </div>
    <div class="col-sm-4 margin-t">
        <div class="alert alert-success text-center margin-b">
            <span class="size-h4">
                The first 100 pre-orders get <b>FREE</b> Tele-Blood Pressure Monitor!
                <br>
                Only <b>20</b> remains! <br>
                <a href="/#pricing">PRE-ORDER now!</a>
            </span>
        </div>
<!--        <div class="panel panel-default margin-b">
            <div class="panel-heading">
                Khuyen mai
            </div>
            <div class="panel-body">
        
            </div>
        </div>-->
        <div class="panel panel-default margin-b">
            <div class="panel-heading">
                Cam nang suc khoe
            </div>
            <div class="panel-body">
                <ul class="nav nav-list">
                    <li><a>Article Title</a></li>
                    <li><a>Article Title</a></li>
                    <li><a>Article Title</a></li>
                    <li><a>Article Title</a></li>
                </ul>
            </div>
        </div>
    </div>
</div>

protected/views/site/article.php
<div class="container">
    <div class="col-sm-12 text-center">
        <h3>Huyết áp - Tim mạch</h3>
    </div>
    <div class="col-sm-8 margin-t article-list">
        <div class="panel panel-default margin-b">
            <div class="panel-heading">
                <a href="/articleDetails">Huyết áp là gì?</a>
            </div>
            <div class="panel-body">
                <img src="/img/article/1do-huyet-ap-190x130.jpg" class="img-thumbnail">
                Có 2 vấn đề sức khỏe đang gây nhức nhối với cộng đồng đó là huyết áp cao và huyết áp thấp. Người ta nhắc nhiều đến các chỉ số “huyết áp” kèm theo thông điệp theo dõi chỉ số huyết áp như theo dõi chính chỉ số sức khỏe của bạn và gia đình. Vậy huyết áp là gì? <a href="/articleDetails">Doc them</a>
            </div>
        </div>
        <div class="panel panel-default margin-b">
            <div class="panel-heading">
                <a href="/articleDetails">Nhận biết sớm các triệu chứng huyết áp cao</a>
            </div>
            <div class="panel-body">
                <img src="/img/article/2816487-190x130.jpeg" class="img-thumbnail">
                Huyết áp cao vô cùng nguy hiểm bởi nó có thể gây ra những ảnh hưởng nghiêm trọng tới sức khỏe và chất lượng cuộc sống. Vì vậy, người bệnh cũng như người thân cần phải trang bị cho mình những hiểu biết nhất định để nhận biết đúng các triệu chứng huyết áp cao, phát hiện và xử trí kịp thời tránh những hậu quả đáng tiếc xảy ra <a href="/articleDetails">Doc them</a>
            </div>
        </div>
    </div>
    <div class="col-sm-4 margin-t">
        <div class="alert alert-success text-center margin-b">
            <span class="size-h4">
                The first 100 pre-orders get <b>FREE</b> Tele-Blood Pressure Monitor!
                <br>
                Only <b>20</b> remains! <br>
                <a href="/#pricing">PRE-ORDER now!</a>
            </span>
        </div>
<!--        <div class="panel panel-default margin-b">
            <div class="panel-heading">
                Khuyen mai
            </div>
            <div class="panel-body">
        
            </div>
        </div>-->
        <div class="panel panel-default margin-b">
            <div class="panel-heading">
                Cam nang suc khoe
            </div>
            <div class="panel-body">
                <ul class="nav nav-list">
                    <li><a>Article Title</a></li>
                    <li><a>Article Title</a></li>
                    <li><a>Article Title</a></li>
                    <li><a>Article Title</a></li>
                </ul>
            </div>
        </div>
    </div>
</div>

protected/views/site/error.php
<?/*php
$this->pageTitle=Yii::app()->name . ' - Error';
$this->breadcrumbs=array(
	'Error',
);*/?>

<div class="container text-center">
    <h1><?php echo $code; ?></h1>

    <?#php echo CHtml::encode($message); ?>
    <p>Oops! The page you looking for doesn't exist!</p>
    
    <a href='/' class='btn btn-primary'>HelloHealth</a>
</div>

protected/views/site/finish.php
<div class="container margin-t">
    <div class="alert alert-default text-center">
        <p class="size-h3">Order successful!</p>
        Thank you for choosing HelloHealth. We will contact you soon!
    </div>
</div>

protected/views/site/z_login.php
<?php
$this->pageTitle=Yii::app()->name . ' - Login';
$this->breadcrumbs=array(
	'Login',
);
?>

<h1>Login</h1>

<p>Please fill out the following form with your login credentials:</p>

<div class="form">
<? $form = $this->beginWidget('CActiveForm') ?>

	<p class="note">Fields with <span class="required">*</span> are required.</p>

	<?= $form->errorSummary($model) ?>

	<div class="row">
		<?= $form->labelEx($model,'username') ?>
		<?= $form->textField($model,'username') ?>
	</div>

	<div class="row">
		<?= $form->labelEx($model,'password') ?>
		<?= $form->passwordField($model,'password') ?>
	</div>

	<div class="row rememberMe">
		<?= $form->checkBox($model,'rememberMe') ?>
		<?= $form->label($model,'rememberMe') ?>
	</div>

	<div class="row">
    <p class="hint"><?= CHtml::link("Lost Password", array('user/reset', 'username'=>$model->username)) ?></p>
	</div>

	<div class="row submit">
		<?= CHtml::submitButton('Login') ?>
	</div>

<? $this->endWidget() ?>
</div><!-- form -->